### ISSUE TITLE
nunchaku-1.1.0+torch2.8-cp312-cp312-win_amd64.whl ?

### ISSUE THREAD

**Issue by SizyKing** [nunchaku-ai/nunchaku#840]
nunchaku-1.1.0+torch2.8-cp312-cp312-win_amd64.whl
I don't see this version? Will it be available or should I switch to another Torch?

**Comment by Myoko** [comment]
needed torch2.7 windows version

**Comment by joneschunghk** [comment]
Last error: Installation failed for https://github.com/nunchaku-tech/nunchaku/releases/download/v1.1.0/nunchaku-1.1.0+torch2.7-cp312-cp312-win_amd64.whl. Error: HTTP Error 404: Not Found

**Comment by LuLmaster69** [comment]
> Last error: Installation failed for https://github.com/nunchaku-tech/nunchaku/releases/download/v1.1.0/nunchaku-1.1.0+torch2.7-cp312-cp312-win_amd64.whl. Error: HTTP Error 404: Not Found

+1

**Comment by Juste-Leo2** [comment]
I don't think automatic build addition will happen because it's quite complex to manage automatic builds on Windows. See #842 

So I compiled various builds myself for CUDA 12.8: [wheel on hugging face](https://huggingface.co/JusteLeo/Nunchaku-Zimage-Win-Wheels)


It's not official, but it worked for me. I hope it works for you too. If not, you may need to consider updating your graphics drivers and your comfyUI environment.

**Comment by SveSop** [comment]
It is not impossible to compile yourself. I was in the same spot for torch2.8.0 and cp312. When you compile yourself, you also just need to use the SM version of your adapter, so the build is not that slow.

PS. @Juste-Leo2 I do recommend building with `--no-deps` , as it (the build system) has a tendency to download "the newest of all dependencies" and that may mess things up down the line.

**Comment by angeloshredder** [comment]
i hope someone will post nunchaku-1.1.0+torch2.8-cp312-cp312-win_amd64.whl , we really don't want to upgrade the torch version, it will ruin all comfyui's addons.

**Comment by arkhub** [comment]
> I don't think automatic build addition will happen because it's quite complex to manage automatic builds on Windows. See [#842](https://github.com/nunchaku-tech/nunchaku/pull/842)
> 
> So I compiled various builds myself for CUDA 12.8: [wheel on hugging face](https://huggingface.co/JusteLeo/Nunchaku-Zimage-Win-Wheels)
> 
> It's not official, but it worked for me. I hope it works for you too. If not, you may need to consider updating your graphics drivers and your comfyUI environment.

thank you, I've tried installing nunchaku wheel for torch 2.7 in your repository but i get this error :

`CUDA error: no kernel image is available for execution on the device (at I:\build_nunchaku\autom\nunchaku\src\kernels\zgemm\gemm_w4a4_launch_impl.cuh:498)`

previous version (1.0.2) worked before.
edit : I don't think I have drive I in my pc, is it path problem?
edit 2 : on your readme there's `set TORCH_CUDA_ARCH_LIST=8.0 8.6 8.9` which I just change it into CUDA that relevant to my system which is Ampere so `set TORCH_CUDA_ARCH_LIST=8.6` fixed the issue for me and I'm able to run the modified build normally.

**Comment by JasonMiao446** [comment]
I want to compile "nunchaku-1.1.0+torch2.7-cp312-cp312-win_amd64.whl", but it failed, and I don't know how to solve it. Here is the error message

ninja: error: 'D:/Python/nunchaku-1.1.0/third_party/Block-Sparse-Attention/csrc/block_sparse_attn/flash_api.cpp', needed by 'D:/Python/nunchaku-1.1.0/build/temp.win-amd64-cpython-312/Release/third_party/Block-Sparse-Attention/csrc/block_sparse_attn/flash_api.obj', missing and no known rule to make it
Traceback (most recent call last):
  File "D:\Python\Python312\Lib\site-packages\torch\utils\cpp_extension.py", line 2595, in _run_ninja_build
    subprocess.run(
  File "D:\Python\Python312\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

**Comment by updownsp** [comment]
i hope someone will post nunchaku-1.1.0+torch2.8-cp311-cp311-win_amd64.whl , we really don't want to upgrade the torch version, it will ruin all comfyui's addons.

**Comment by arkhub** [comment]
> I want to compile "nunchaku-1.1.0+torch2.7-cp312-cp312-win_amd64.whl", but it failed, and I don't know how to solve it. Here is the error message
> 
> ninja: error: 'D:/Python/nunchaku-1.1.0/third_party/Block-Sparse-Attention/csrc/block_sparse_attn/flash_api.cpp', needed by 'D:/Python/nunchaku-1.1.0/build/temp.win-amd64-cpython-312/Release/third_party/Block-Sparse-Attention/csrc/block_sparse_attn/flash_api.obj', missing and no known rule to make it Traceback (most recent call last): File "D:\Python\Python312\Lib\site-packages\torch\utils\cpp_extension.py", line 2595, in _run_ninja_build subprocess.run( File "D:\Python\Python312\Lib\subprocess.py", line 571, in run raise CalledProcessError(retcode, process.args, subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

I have similar problem when trying to compile, turns out some third party folder are empty, and I have to do this : `git submodule update --init --recursive` in main nunchaku folder (make sure the nunchaku source are from git clone not manually download)

**Comment by shnaps666** [comment]
Torch2.7+Python3.12 
[https://huggingface.co/datasets/paredeyes/3D_extras/resolve/main/nunchaku-1.1.0%2Btorch2.7-cp312-cp312-win_amd64.whl](url)
Torch2.8+Python3.12
[https://huggingface.co/datasets/paredeyes/3D_extras/resolve/main/nunchaku-1.1.0%2Btorch2.8-cp312-cp312-win_amd64.whl](url)

**Comment by Juste-Leo2** [comment]
> > I don't think automatic build addition will happen because it's quite complex to manage automatic builds on Windows. See [#842](https://github.com/nunchaku-tech/nunchaku/pull/842)
> > So I compiled various builds myself for CUDA 12.8: [wheel on hugging face](https://huggingface.co/JusteLeo/Nunchaku-Zimage-Win-Wheels)
> > It's not official, but it worked for me. I hope it works for you too. If not, you may need to consider updating your graphics drivers and your comfyUI environment.
> 
> thank you, I've tried installing nunchaku wheel for torch 2.7 in your repository but i get this error :
> 
> `CUDA error: no kernel image is available for execution on the device (at I:\build_nunchaku\autom\nunchaku\src\kernels\zgemm\gemm_w4a4_launch_impl.cuh:498)`
> 
> previous version (1.0.2) worked before. edit : I don't think I have drive I in my pc, is it path problem? edit 2 : on your readme there's `set TORCH_CUDA_ARCH_LIST=8.0 8.6 8.9` which I just change it into CUDA that relevant to my system which is Ampere so `set TORCH_CUDA_ARCH_LIST=8.6` fixed the issue for me and I'm able to run the modified build normally.

I understand the problem now. I forgot to pass the argument set NUNCHAKU_INSTALL_MODE=ALL, which is specific to Nunchaku. My bad. I'll update my wheels, and soon it should work for everyone on [Hugging Face](https://huggingface.co/JusteLeo/Nunchaku-Zimage-Win-Wheels) :)

Edit: The current builds on Hugging Face only work for RTX 40xx. Compilations take longer, so you'll have to wait a while for the builds to be updated.

Edit2: The compilation will only support versions for the 3000 and 4000 series. For the 5000 series, use a more recent version of PyTorch, which I think is better and more optimized. For the 2000 series, Zimage is not officially supported, so there is no point in compiling it.

**Comment by Juste-Leo2** [comment]
I've updated all the [wheels](https://huggingface.co/JusteLeo/Nunchaku-Zimage-Win-Wheels), I hope that helps. Normally, it should support the RTX 3000 and 4000 series.

@arkhub You can try installing the wheels again if you want, it should work normally. For that, you can use the `--force-reinstall` argument with pip.

**Comment by arkhub** [comment]
> I've updated all the [wheels](https://huggingface.co/JusteLeo/Nunchaku-Zimage-Win-Wheels), I hope that helps. Normally, it should support the RTX 3000 and 4000 series.
> 
> [@arkhub](https://github.com/arkhub) You can try installing the wheels again if you want, it should work normally. For that, you can use the `--force-reinstall` argument with pip.

I've tested the new build (the size looks bigger?) then encounter this error when clean installing  : 
`ERROR: nunchaku-1.1.0+torch2.7-cp312-cp312-win_amd64.whl is not a supported wheel on this platform.` 
even though it's the correct platform for me (Ampere GPU with Torch 2.7.1 and Cuda 12.8)

**Comment by Juste-Leo2** [comment]
> > I've updated all the [wheels](https://huggingface.co/JusteLeo/Nunchaku-Zimage-Win-Wheels), I hope that helps. Normally, it should support the RTX 3000 and 4000 series.
> > [@arkhub](https://github.com/arkhub) You can try installing the wheels again if you want, it should work normally. For that, you can use the `--force-reinstall` argument with pip.
> 
> I've tested the new build (the size looks bigger?) then encounter this error when clean installing : `ERROR: nunchaku-1.1.0+torch2.7-cp312-cp312-win_amd64.whl is not a supported wheel on this platform.` even though it's the correct platform for me (Ampere GPU with Torch 2.7.1 and Cuda 12.8)

For the compilation, I used Torch 2.7.0 (I don't think that's related to the problem). The size is larger because I compiled with CUDA 12.8, and it contains several architectures.
Do you have any more detailed logs?

@arkhub Can you try adding the `--no-deps` argument?

**Comment by luckyu445** [comment]
> Torch2.7+Python3.12 [https://huggingface.co/datasets/paredeyes/3D_extras/resolve/main/nunchaku-1.1.0%2Btorch2.7-cp312-cp312-win_amd64.whl](url) Torch2.8+Python3.12 [https://huggingface.co/datasets/paredeyes/3D_extras/resolve/main/nunchaku-1.1.0%2Btorch2.8-cp312-cp312-win_amd64.whl](url)

Thank you! It works perfectly.

**Comment by arkhub** [comment]
> > > I've updated all the [wheels](https://huggingface.co/JusteLeo/Nunchaku-Zimage-Win-Wheels), I hope that helps. Normally, it should support the RTX 3000 and 4000 series.
> > > [@arkhub](https://github.com/arkhub) You can try installing the wheels again if you want, it should work normally. For that, you can use the `--force-reinstall` argument with pip.
> > 
> > 
> > I've tested the new build (the size looks bigger?) then encounter this error when clean installing : `ERROR: nunchaku-1.1.0+torch2.7-cp312-cp312-win_amd64.whl is not a supported wheel on this platform.` even though it's the correct platform for me (Ampere GPU with Torch 2.7.1 and Cuda 12.8)
> 
> For the compilation, I used Torch 2.7.0 (I don't think that's related to the problem). The size is larger because I compiled with CUDA 12.8, and it contains several architectures. Do you have any more detailed logs?
> 
> [@arkhub](https://github.com/arkhub) Can you try adding the `--no-deps` argument?

nope, the output is just that no other information. I also try `--no-deps` when installing but the error stays the same.

**Comment by zraul** [comment]
I hope someone will post nunchaku-1.1.0+torch2.7-cp310-cp310-win_amd64.whl

**Comment by juntaosun** [comment]
I hope someone will post nunchaku-1.1.0+torch2.8-cp313-cp313-win_amd64.whl

Resolved~
https://huggingface.co/JusteLeo/Nunchaku-Zimage-Win-Wheels/tree/main

**Comment by shnaps666** [comment]
Torch2.7+Python3.10
[https://huggingface.co/datasets/paredeyes/3D_extras/resolve/main/nunchaku-1.1.0%2Btorch2.7-cp310-cp310-win_amd64.whl](url)
Torch2.8+Python3.11
[https://huggingface.co/datasets/paredeyes/3D_extras/resolve/main/nunchaku-1.1.0%2Btorch2.8-cp311-cp311-win_amd64.whl](url)

**Comment by TJundx** [comment]
> I hope someone will post nunchaku-1.1.0+torch2.8-cp313-cp313-win_amd64.whl
> 
> Resolved~ https://huggingface.co/JusteLeo/Nunchaku-Zimage-Win-Wheels/tree/main

I used 2.8+312 in this directory, and it will report this error 'RuntimeError: CUDA error: no kernel image is available for execution on the device' at runtime, and my cuda and pytorch are adapted. When I switched the wheel to version 1.02, this worked fine again,
It shows that there is still a problem with this 1.1.0 wheel

**Comment by shnaps666** [comment]
Torch2.8+Python3.13
https://huggingface.co/datasets/paredeyes/3D_extras/resolve/main/nunchaku-1.2.0.dev20260104%2Btorch2.8-cp313-cp313-win_amd64.whl
Torch2.9+Python3.13
https://huggingface.co/datasets/paredeyes/3D_extras/resolve/main/nunchaku-1.2.0.dev20260104%2Btorch2.9-cp313-cp313-win_amd64.whl

**Comment by null-walker** [comment]
> Torch2.7+Python3.12 [https://huggingface.co/datasets/paredeyes/3D_extras/resolve/main/nunchaku-1.1.0%2Btorch2.7-cp312-cp312-win_amd64.whl](url) Torch2.8+Python3.12 [https://huggingface.co/datasets/paredeyes/3D_extras/resolve/main/nunchaku-1.1.0%2Btorch2.8-cp312-cp312-win_amd64.whl](url)

you're the hero,save my day! my rtx5060 works.
